import obstore
from rapida.ntl.noaa.const import PRODUCTS, PRODUCT_NAMES, VIIRS_URLS,PUBLIC_CONFIG,SOURCE_NAMES
from datetime import datetime, timedelta
from typing import Iterable
import random
import logging
from rapida.ntl.noaa.cmask import bbox_in_hdf
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


def parse_noaa_timestamp(time_str: str) -> datetime:
    """
    Converts a NOAA VIIRS string (e.g., '202604010001018') into a timezone-naive UTC datetime.
    """
    # The first 14 characters: YYYYMMDDHHMMSS
    base_time = datetime.strptime(time_str[:14], "%Y%m%d%H%M%S")

    # The 15th character: tenths of a second (1 tenth = 100,000 microseconds)
    tenths = int(time_str[14:])

    return base_time + timedelta(microseconds=tenths * 100000)


def public_url(file_path:str=None, satellite:str=None, source:str=None):

    public_cloud_url = VIIRS_URLS[satellite][source]
    parsed_public_url = urlparse(public_cloud_url)
    bucket = parsed_public_url.netloc
    if parsed_public_url.scheme == 's3':
        return f'https://{bucket}.s3.amazonaws.com/{file_path}'
    if parsed_public_url.scheme == 'gs':
        return f'https://storage.googleapis.com/{bucket}/{file_path}'


async def find_ntl(satellite: str = None, bbox: Iterable[float] = None, dt: datetime = None,
                   products: Iterable[str] = PRODUCT_NAMES, source: str = None):
    found = {}

    # The "Solid" way: Generate stores using from_url
    viirs_stores = {
        sat: {
            source: obstore.store.from_url(url, config=PUBLIC_CONFIG)
            for source, url in sources.items()
        }
        for sat, sources in VIIRS_URLS.items()
    }


    stores = viirs_stores[satellite]

    # 1. Safely determine the primary and alternate sources
    primary_source = source if source else random.choice(SOURCE_NAMES)
    alt_source = SOURCE_NAMES[0] if primary_source == SOURCE_NAMES[1] else SOURCE_NAMES[1]

    # Calculate target times upfront to handle rollovers safely
    target_dts = [dt, dt - timedelta(minutes=1), dt + timedelta(minutes=1)]
    for product_name in products:
        product = PRODUCTS[product_name]
        sources_to_try = [primary_source, alt_source]

        # Track time patterns that we know missed the bounding box
        spatial_misses = set()
        match_found = False

        for current_source in sources_to_try:
            store = stores[current_source]
            entries_cache = {}

            for sc_dt in target_dts:
                # Format the time pattern dynamically based on the specific offset
                time_pattern = sc_dt.strftime('s%Y%m%d%H%M' if 'cloud' in product.lower() else 't%H%M')

                # Instantly skip if we already proved this timestamp misses the bbox on a previous source
                if time_pattern in spatial_misses:
                    continue

                date_path = sc_dt.strftime('/%Y/%m/%d/')
                prefix = f"{product}{date_path}"

                # Cache listed entries by prefix so we don't make duplicate network calls
                if prefix not in entries_cache:
                    entries_cache[prefix] = await obstore.list(store, prefix=prefix).collect_async()

                entries = entries_cache[prefix]

                if not entries:
                    continue

                try:
                    selected_entry = [e for e in entries if time_pattern in e['path'] and (
                                e['path'].endswith('.nc') or e['path'].endswith('.h5'))].pop()
                    file_path, file_size = selected_entry['path'], selected_entry['size']
                    public_file_url = public_url(file_path=file_path, satellite=satellite, source=current_source)
                    if not bbox_in_hdf(hdf_url=public_file_url,bbox=bbox):
                        logger.debug(
                            f'Skipping {file_path} from {current_source} generated by {satellite} because it does not intersect {bbox} bbox')
                        spatial_misses.add(time_pattern)
                        continue

                    if current_source not in found: #reset
                        found[current_source] = []

                    found[current_source].append((file_path, file_size))
                    match_found = True
                    break

                except IndexError:
                    logger.debug(
                        f'No exact match for satellite {satellite} timestamp {time_pattern} on {store}. Considering temporal neighbors.')

                    continue

            if match_found:
                break

        if not match_found:
            logger.debug(
                f'No valid/intersecting data for product {product} and satellite {satellite} for the night {dt}')


    return found