[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
rapida = { path = "." }

[pypi-dependencies]
dotenv-cli = "*"

[activation.env]
PLAYWRIGHT_BROWSERS_PATH = ".pixi/playwright-browsers"

[tasks]
setup = "dotenv -e .env playwright install chromium --only-shell"
rapida = "dotenv -e .env rapida"

[package]
name = "rapida"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.*" }

[package.host-dependencies]
setuptools = ">=61.0"
setuptools_scm = ">=8.0"

[package.run-dependencies]
python = ">=3.12"
gdal = ">=3.12.0"
osmium-tool = ">=1.19.1"
h5py = ">=3.11.0"
libgdal-netcdf = "*"