name: Build docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    env:
      IMAGE_NAME: ${{ github.repository }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: prod
          outputs: type=docker,dest=${{ runner.temp }}/myimage-${{ matrix.arch }}.tar
      - name: Upload ${{ matrix.arch }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage-${{ matrix.arch }}
          path: ${{ runner.temp }}/myimage-${{ matrix.arch }}.tar

  test:
    name: Test CLI
    needs: build-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage-${{ matrix.arch }}
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage-${{ matrix.arch }}.tar
          docker image ls -a

      - name: Run tests in container
        run: |
          docker run --rm \
            --platform linux/${{ matrix.arch }} \
            -e USER=docker \
            --entrypoint /bin/bash \
            ${{ needs.build-image.outputs.tags }} \
            -c "pipenv run pip install .[dev] && pipenv run python -m pytest tests"

  deploy-acr:
    name: Build and deploy to Azure Container Registry
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')}}
    needs: build-image
    runs-on: ubuntu-latest
    environment:
      name: azure container registry
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage-${{ matrix.arch }}
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage-${{ matrix.arch }}.tar
          docker image ls -a

      - name: Log into ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Load Docker image and push to ACR
        run: |
          docker tag ${{ needs.build-image.outputs.tags }} ${{ secrets.ACR_ENDPOINT }}/${{ needs.build-image.outputs.tags }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ needs.build-image.outputs.tags }} --platform ${{ matrix.arch }}

  deploy-github:
    name: Build and deploy to GitHub container registry
    # if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')}}
    needs: build-image
    runs-on: ubuntu-latest
    environment:
      name: github container registry
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage-${{ matrix.arch }}
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage-${{ matrix.arch }}.tar
          docker image ls -a

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Docker image and push to Container Registry
        run: |
          docker tag ${{ needs.build-image.outputs.tags }} ${{ env.REGISTRY }}/${{ needs.build-image.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ needs.build-image.outputs.tags }} --platform ${{ matrix.arch }}
