name: Build docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

env:
  REGISTRY_IMAGE: ${{ github.repository }}

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ${{ matrix.runner }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            arch: amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            arch: arm64
            runner: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: prod
          outputs: type=image,push-by-digest=true,name-canonical=true,push=false

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge multi-platform images
    runs-on: ubuntu-latest
    needs: build-image
    outputs:
      image-name: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.merge.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create manifest list locally
        id: merge
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create --dry-run $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          # Get the digest of the merged manifest
          DIGEST=$(docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }} --format '{{.Manifest.Digest}}')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Export merged image
        run: |
          # Save the merged image as a tar file
          docker save ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }} -o ${{ runner.temp }}/merged-image.tar

      - name: Upload merged image
        uses: actions/upload-artifact@v4
        with:
          name: merged-image-${{ steps.meta.outputs.version }}
          path: ${{ runner.temp }}/merged-image.tar
          if-no-files-found: error
          retention-days: 1

  test:
    name: Test CLI
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download merged image
        uses: actions/download-artifact@v4
        with:
          name: merged-image-${{ needs.merge.outputs.image-name }}
          path: ${{ runner.temp }}/merged-image.tar

      - name: Load Docker image
        run: |
          docker load -i ${{ runner.temp }}/merged-image.tar

      - name: Test amd64 image
        run: |
          docker run --rm \
            --platform linux/amd64 \
            -e USER=docker \
            --entrypoint /bin/bash \
            ${{ env.REGISTRY_IMAGE }}:${{ needs.merge.outputs.image-name }} \
            -c "pipenv run pip install .[dev] && pipenv run python -m pytest tests"

  deploy-acr:
    name: Build and deploy to Azure Container Registry
    # if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')}}
    needs: merge
    runs-on: ubuntu-latest
    environment:
      name: azure container registry
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download merged image
        uses: actions/download-artifact@v4
        with:
          name: merged-image-${{ needs.merge.outputs.image-name }}
          path: ${{ runner.temp }}/merged-image.tar

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage.tar
          docker image ls -a

      - name: Log into ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Load Docker image and push to ACR
        run: |
          docker tag ${{ needs.build-image.outputs.tags }} ${{ secrets.ACR_ENDPOINT }}/${{ needs.build-image.outputs.tags }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ needs.build-image.outputs.tags }}

  deploy-github:
    name: Build and deploy to GitHub container registry
    # if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')}}
    needs: merge
    runs-on: ubuntu-latest
    environment:
      name: github container registry
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download merged image
        uses: actions/download-artifact@v4
        with:
          name: merged-image-${{ needs.merge.outputs.image-name }}
          path: ${{ runner.temp }}/merged-image.tar

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage.tar
          docker image ls -a

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Docker image and push to ACR
        run: |
          docker tag ${{ needs.build-image.outputs.tags }} ${{ env.REGISTRY }}/${{ needs.build-image.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ needs.build-image.outputs.tags }}
